version: '3.8'
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    ports:
      - 6379:6379
  web:
    image: harbor.dndev.pw:4443/mysns/web:latest
    restart: always
    # 필요시 볼륨 마운팅
    # volumes: 
    #   - /dev:/dev
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 
    ports:
      - 80:80
      # 인증서 준비될 경우 반영
      # - 443:443
    deploy:
      replicas: 1
    environment:
      - SERVICE=production
      - DOMAIN=mysns.info
    networks:
      - bridge

networks:
  bridge:
    external:
      name: bridge