name: Agent CI

on:
  push:
    branch: [dev_jis]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build docker image
      run: docker build . --file DockerfileScraper

  deploy:
    needs: build

    runs-on: ubuntu-latest
    
    # login to harbor
    steps:
    - name: Login harbor
      uses: docker/login-action@v1
      with:
        registry: harbor.dndev.pw:4443
        username: ${{ secrets.HARBOR_BOT_ID }}
        password: ${{ secrets.HARBOR_BOT_PW }}

    - name: Push docker image
      run: docker push harbor.dndev.pw:4443/mysns/scraper:latest
