name: Agent CI

on:
  push:
    branch: [dev_jis]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: harbor.dndev.pw:4443
        username: ${{ secrets.HARBOR_BOT_ID }}
        password: ${{ secrets.HARBOR_BOT_PW }}

    - name: Docker image build and push
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./DockerfileScraper
        tags: harbor.dndev.pw:4443/mysns/scraper:latest
        outputs: type=oci,dest=/tmp/image.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: myimage
        path: /tmp/myimage.tar

      # run: docker build . --file DockerfileScraper --tag harbor.dndev.pw:4443/mysns/scraper:latest

    # building image store
    # - name: share docker image
    #   uses: actions/download-artifact@v2
    #   with:
    #     path: var/libs/docker

  deploy:
    runs-on: ubuntu-latest

    needs: build    
    
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: myimage
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a

  
    
  #   steps:
  #   # checkout git repository
  #   - uses: actions/checkout@v2

  #   # share docker images
  #   - name: share docker image
  #     uses: actions/download-artifact@v2
  #     with:
  #       path: var/libs/docker

  #   - name: check docker images
  #     run: docker images

    

  #   # authorize ssl certificates for login
  #   - name: set cert
  #     run: |
  #       bash cert.sh
  #     # ls -al mySns/mySns/build/libs

  #   # login to harbor
  #   - name: Login harbor
  #     uses: docker/login-action@v1
  #     with:
  #       registry: harbor.dndev.pw:4443
  #       username: ${{ secrets.HARBOR_BOT_ID }}
  #       password: ${{ secrets.HARBOR_BOT_PW }}

  #   - name: Push docker image
  #     run: docker push harbor.dndev.pw:4443/mysns/scraper:latest
