name: Agent CI

on:
  push:
    branch: [dev_jis]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image test
      run: docker build . --file Dockerfile_scraper -t scraper


