name: Agent CI

on:
  push:
    branch: [dev_jis]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # authorize ssl certificates for login
    - name: set cert
      run: |
        bash cert.sh
      # ls -al mySns/mySns/build/libs

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: harbor.dndev.pw:4443
        username: ${{ secrets.HARBOR_BOT_ID }}
        password: ${{ secrets.HARBOR_BOT_PW }}
    # Build the Docker image as tar file
    - name: Docker image build and push
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./DockerfileScraper
        tags: harbor.dndev.pw:4443/mysns/scraper:latest
        outputs: type=oci,dest=/tmp/myimage.tar

    - name: Show Docker image
      run: ls -la /tmp/ 

    # building image upload
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: myimage
        path: /tmp/myimage.tar

      # run: docker build . --file DockerfileScraper --tag harbor.dndev.pw:4443/mysns/scraper:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build    
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Download the tar file of Docker image
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: myimage
          path: /tmp

      # unzip the tar file to Docker image
      - name: Load Docker image
        run: |
          docker load < /tmp/myimage.tar
          docker image ls -a

      # Upload the Docker image to "Harbor"
      - name: Push the docker image
        run: docker push harbor.dndev.pw:4443/mysns/scraper:latest

  
    
  #   steps:
  #   # checkout git repository
  #   - uses: actions/checkout@v2

  #   # share docker images
  #   - name: share docker image
  #     uses: actions/download-artifact@v2
  #     with:
  #       path: var/libs/docker

  #   - name: check docker images
  #     run: docker images

    

  #   # authorize ssl certificates for login
  #   - name: set cert
  #     run: |
  #       bash cert.sh
  #     # ls -al mySns/mySns/build/libs

  #   # login to harbor
  #   - name: Login harbor
  #     uses: docker/login-action@v1
  #     with:
  #       registry: harbor.dndev.pw:4443
  #       username: ${{ secrets.HARBOR_BOT_ID }}
  #       password: ${{ secrets.HARBOR_BOT_PW }}

  #   - name: Push docker image
  #     run: docker push harbor.dndev.pw:4443/mysns/scraper:latest
