name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x ./mySns/mySns/gradlew
      
    - name: Build with Gradle
      run: ./mySns/mySns/gradlew clean build
  build-if-failed:
    runs-on: ubuntu-latest
    needs: [build]
    if: always() && (needs.build.result == 'failure')
    steps:
      - name: pre excute failed
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          echo "$NEEDS_CONTEXT"
      - name: Slack Notification Failed
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#FF2D00' # or a specific color like 'good' or '#ff00ff'
#           SLACK_ICON: https://github.com/rtCamp.png?size=48 # later add favicon
          SLACK_TITLE: 'Preexcute python script was failed'
          SLACK_MESSAGE: ${{ github.event.head_commit.title }} ${{ github.event.head_commit.message }}
          SLACK_USERNAME: ANC-mysns-Podo
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
